[package]
name = "cv"
version = "0.1.0"
authors = ["j-keck <jhyphenkeck@gmail.com>"]
edition = "2018"

[dependencies]
opencv = { version = "0.30" }
log = "0.4"
crossbeam-channel = "0.4.2"
snafu = "0.6.2"
serde = { version = "1.0.104", features = [ "derive" ] }
xstd = "0.2"